
#utiliza una imagen base de Ubuntu 
FROM ubuntu:latest

# Instala dependencias necesarias
RUN apt-get update && \
apt-get install -y file

# Crea un directorio para almacenar archivos clasificados
RUN mkdir -p /app/outputs/img /app/outputs/snd /app/outputs/txt

# Copia los scripts y archivos necesarios al contenedor

COPY menu.sh /app/

COPY opt/src/clasificador.sh /app/

COPY organizador_archivos.sh /app/

COPY opt/src/analizar_textos.sh /app/

COPY opt/src/encontrar_correos.sh /app/

COPY opt/src/long_palabras.sh /app/

COPY opt/src/palindromo.sh /app/

COPY monitor.sh /app/

# Ejecuta el script menu.sh cuando se inicia el contenedor
CMD ["/bin/bash", "/app/menu.sh"]i
