
# Use an official Ubuntu runtime as a parent image
FROM ubuntu:latest

# Install necessary packages
RUN apt-get update && \
apt-get install -y file

# Create a directory to store classified files
RUN mkdir -p /app/outputs/img /app/outputs/snd /app/outputs/txt

# Copy the clasificador.sh script into the container
COPY menu.sh /app/

COPY opt/src/clasificador.sh /app/

COPY organizador_archivos.sh /app/

COPY opt/src/analizar_textos.sh /app/

COPY opt/src/encontrar_correos.sh /app/

COPY opt/src/long_palabras.sh /app/

COPY opt/src/palindromo.sh /app/

COPY monitor.sh /app/

# Run the clasificador.sh script
CMD ["/bin/bash", "/app/menu.sh"]i
